name: Hello World
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: 'echo "Hello, World!"'
