name: Run React Native App

on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo Xvfb :99 -ac -screen 0 1280x1024x16 &
        env:
          DISPLAY: :99

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools
          unzip commandlinetools-linux-6609375_latest.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          emulator-options: '-no-window -no-audio'
          script: adb shell input keyevent 82

      - name: Validate Emulator is Running
        run: |
          for i in {1..30}; do adb shell getprop init.svc.bootanim | grep -e 'stopped' && break || sleep 10; done
          adb devices

      - name: Install Watchman
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/facebook/watchman/releases/download/v2022.10.10.00/watchman-v2022.10.10.00-linux.zip
          unzip watchman-v2022.10.10.00-linux.zip -d watchman
          sudo cp watchman/bin/* /usr/local/bin/
          sudo chmod +x /usr/local/bin/watchman
          watchman --version

      - name: Install CocoaPods (macOS only)
        if: runner.os == 'macOS'
        run: |
          sudo gem install cocoapods

      - name: Start Metro Bundler
        run: npx react-native start &
        continue-on-error: true

      - name: Run Android Build
        run: npx react-native run-android
        env:
          DISPLAY: :99
        continue-on-error: true

      - name: Run iOS Build (macOS only)
        if: runner.os == 'macOS'
        run: npx react-native run-ios
        continue-on-error: true
