name: Run React Native App

on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo Xvfb :99 -ac -screen 0 1280x1024x16 &
        env:
          DISPLAY: :99

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          emulator-options: '-no-window -no-audio'

      - name: Wait for Android Emulator
        run: |
          adb wait-for-device
          adb shell input keyevent 82

      - name: Install Watchman
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential python-dev libtool libssl-dev
          git clone https://github.com/facebook/watchman.git
          cd watchman
          git checkout v4.9.0
          ./autogen.sh
          ./configure
          make
          sudo make install

      - name: Install CocoaPods (macOS only)
        if: runner.os == 'macOS'
        run: |
          sudo gem install cocoapods

      - name: Start Metro Bundler
        run: npx react-native start &
        continue-on-error: true

      - name: Run Android Build
        run: npx react-native run-android
        env:
          DISPLAY: :99
        continue-on-error: true

      - name: Run iOS Build (macOS only)
        if: runner.os == 'macOS'
        run: npx react-native run-ios
        continue-on-error: true
